version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - D:/pagerr-data/postgres:/var/lib/postgresql/data
    env_file:
      - docker.env.development
    networks:
      - postgres
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8080:80
    volumes:
      - D:/pagerr-data/pgadmin:/var/lib/pgadmin
    env_file:
      - docker.env.development
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
